<?php
//////////////// Site Configuration ////////////////
  $TITLE = 'Micro Content Management System';
  $DEFLANG = 'en';
//$COPYNOTE = 'Copyright &copy; 2025';
//$DOCROOT = '';
  $MAINPAGE = 'main';
//$NAVPAGE = 'nav';
//$PAGE404 = '404';
//////////////// Markdown Configuration ////////////////
//$TAB_WIDTH=4;
//$HARD_WRAP=false;
//$NO_MARKUP=false;
//$NO_ENTITIES=false;
//$PREDEF_URLS=array('ucms-home' => 'https://www.jadaml.website/ucms');
//$PREDEF_TITLES=array('ucms-home' => 'µCMS Home');
//$URL_FILTER_FUNC=function ($url) { return $url; };
//$HEADER_ID_FUNC=null;
//$CODE_BLOCK_CONTENT_FUNC=null;
//$CODE_SPAN_CONTENT_FUNC=null;
//$ENHANCED_ORDERED_LIST=true;
//$FN_LINK_CLASS='footnote-ref';
//$FN_BACKLINK_CLASS='footnote-backref';
//$FN_BACKLINK_LABEL='';
  $FN_BACKLINK_HTML='&#8617;' . chr(0xFE0E);
  $CODE_CLASS_PREFIX='language-';
//$CODE_ATTR_ON_PRE=false;
//$TABLE_ALIGN_CLASS_TMPL='align-%%';
  $PREDEF_ABBR=array('CMS' => 'Content Management System', 'µCMS' => 'Micro Content Management System', 'CC' => 'Creative Commons');
//$HASHTAG_PROTECTION=false;
//////////////// SmartyPants Configuration ////////////////
//$TAGS_TO_SKIP = 'pre|code|kbd|script|style|math';
//$DO_NOTHING=false;
//$DO_QUOTES=1;
  $DO_BACKTICKS=2;
  $DO_DASHES=2;
//$DO_ELLIPSES=1;
  $CONVERT_QUOT=1;
//$SMART_DOUBLEQUOTE_OPEN = '&#8220;';
//$SMART_DOUBLEQUOTE_CLOSE = '&#8221;';
//$SMART_SINGLEQUOTE_OPEN = '&#8216;';
//$SMART_SINGLEQUOTE_CLOSE = '&#8217;';
//$BACKTICK_DOUBLEQUOTE_OPEN = '&#8220;';
//$BACKTICK_DOUBLEQUOTE_CLOSE = '&#8221;';
//$BACKTICK_SINGLEQUOTE_OPEN = '&#8216;';
//$BACKTICK_SINGLEQUOTE_CLOSE = '&#8217;';
//$EM_DASH = '&#8212;';
//$EN_DASH = '&#8211;';
//$ELLIPSIS = '&#8230;';
  $DO_COMMA_QUOTES=1;
  $DO_GUILLEMETS=1;
//$DO_GERESH_GERSHAYIM=1;
//$DO_SPACE_COLON=1;
//$DO_SPACE_SEMICOLON=1;
//$DO_SPACE_MARKS=1;
//$DO_SPACE_EMDASH=1;
//$DO_SPACE_ENDASH=1;
//$DO_SPACE_FRENCHQUOTE=1;
//$DO_SPACE_THOUSANDS=2;
  $DO_SPACE_UNIT=2;
//$DO_SPACE_PERCENT=1;
//$DOUBLEQUOTE_LOW='&#8222;';
//$GUILLEMET_LEFTPOINTING = '&#171;';
//$GUILLEMET_RIGHTPOINTING = '&#187;';
//$GERESH = '&#1523;';
//$GERSHAYIM = '&#1524;';
//$SPACE_EMDASH = ' ';
//$SPACE_ENDASH = ' ';
//$SPACE_COLON = '&#160;';
//$SPACE_SEMICOLON = '&#160;';
//$SPACE_MARKS = '&#160;';
//$SPACE_FRENCHQUOTE = '&#160;';
//$SPACE_THOUSAND = '&#160;';
//$SPACE_UNIT = '&#160;';
//$SPACE = '(?: | |&nbsp;|&#0*160;|&#x0*[aA]0;)';
?>